### ISSUE TITLE
Error in signin

### ISSUE THREAD

**Issue by nadiryuceer** [erdemgonul/ecommerce-chain#1]
There is an internal error in server while signing in with true credentials. Here's a short description of the error server logged:

(node:9248) UnhandledPromiseRejectionWarning: Error: secretOrPrivateKey must have a value

**Comment by OguzErtanAyanlar** [comment]
You need to have a .env file containing JWT_SECRET, and run the server with command **npm run dev** here is a sample .env file:

> NODE_ENV=development
> DATABASE_HOST=localhost
> DATABASE_PORT=27017
> DATABASE_DB=ecommerce_chain
> JWT_SECRET=jwtSecret
> ACCESS_TOKEN_EXPIRY_TIME=1h
